# Site settings
title: Pi
email: vphuc.p@gmail.com
description: "My blog."
baseurl: ""
url: "pvanphuc.github.io"
twitter_username: Pi
github_username:  pvanphuc

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

